sudo: required
services:
  - docker

before_install:
  - docker build -t mradman123/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true mradman123/docker-react npm run test

deploy:
  - provider: elasticbeanstalk
  - region: "eu-west-3"
  - app: "docker-react"
  - env: "DockerReact-env"
  - bucket_name: "elasticbeanstalk-eu-west-3-976230332130"
  - bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
